stages:
  - test
  - deploy

before_script:
  - npm ci

test:
  image: cypress/base:latest
  stage: test
  script:
    - npm run gather-licenses &
    - npm start &
    - npm run test
  artifacts:
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

pages:
  image: node:lts
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - main
