stages:
  - deploy

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying files using FTP..."
    - apt-get update -qq && apt-get install -qq lftp
    - lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST -e "set ftp:ssl-force true; set ssl:check-hostname false; mirror --delete $LOCAL_DIR $REMOTE_DIR; quit"
    - echo "Files deployed successfully."
