stages:
  - deploy

deploy-job:
  stage: deploy
  environment: production
  only:
    - main
  script:
    - echo "Deploying files using FTP..."
    - apt-get update -qq && apt-get install -qq lftp
    - lftp -e "set ftp:ssl-force true ; set ssl:verify-certificate false ; mirror --delete $LOCAL_DIR $REMOTE_DIR ; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
    - echo "Files deployed successfully."