stages:
  - deploy

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying files using FTP..."
    - apt update -qq && apt install -qq lftp 
    - lftp "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_URL; mirror --continue --reverse --delete $LOCAL_DIR $REMOTE_DIR"
    - echo "Files deployed successfully."
